// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_brother_its_been_too_long = "CgkIx4L88PIFEAIQCw"; // <GPGSID>
        public const string achievement_experiment_626 = "CgkIx4L88PIFEAIQAw"; // <GPGSID>
        public const string achievement_the_tree_that_hides_the_worm = "CgkIx4L88PIFEAIQAg"; // <GPGSID>
        public const string achievement_the_great_escape = "CgkIx4L88PIFEAIQBw"; // <GPGSID>
        public const string achievement_beginning_of_an_adventure = "CgkIx4L88PIFEAIQAQ"; // <GPGSID>
        public const string achievement_be_careful_with_that = "CgkIx4L88PIFEAIQDA"; // <GPGSID>
        public const string achievement_run_asticosmic_run = "CgkIx4L88PIFEAIQBQ"; // <GPGSID>
        public const string achievement_light_speed = "CgkIx4L88PIFEAIQCA"; // <GPGSID>
        public const string achievement_world_record = "CgkIx4L88PIFEAIQCQ"; // <GPGSID>
        public const string achievement_what_is_this_place = "CgkIx4L88PIFEAIQDQ"; // <GPGSID>
        public const string achievement_are_you_lost = "CgkIx4L88PIFEAIQDg"; // <GPGSID>
        public const string achievement_lets_speed_up_deforestation = "CgkIx4L88PIFEAIQBg"; // <GPGSID>
        public const string achievement_the_cosmic_worm = "CgkIx4L88PIFEAIQBA"; // <GPGSID>
        public const string achievement_baby_steps = "CgkIx4L88PIFEAIQCg"; // <GPGSID>

}

